version: "3.7"

services:
    app:
        container_name: api-sisamorim
        image: laravel-app
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html
        depends_on:
            - redis
        networks:
            - rede_web_docker
# nginx
    nginx:
        container_name: nginx-sisamorim
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 9001:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - rede_web_docker
# db mysql
    # mysql:
    #     image: mysql:5.7
    #     container_name: mysql-sisamorim
    #     restart: unless-stopped
    #     environment:
    #        - MYSQL_ROOT_PASSWORD=root
    #        - MYSQL_DATABASE=sisamorim
    #     volumes:
    #         - ./.docker/mysql/dbdata:/var/lib/mysql
    #     ports:
    #         - 3307:3306
    #     networks:
    #         - rede_web_docker

# redis
    redis:
        container_name: redis-sisamorim
        image: redis:latest
        networks:
            - rede_web_docker

networks:
    rede_web_docker:
        name: rede_web_docker
        driver: bridge
