version: "3.7"

services:
    # image project
    app:
        container_name: api-sisamorim
        image: laravel-app
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html
        depends_on:
            - redis
        networks:
            - rede_sisamorim

    # nginx
    nginx:
        container_name: nginx-sisamorim
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 9001:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - rede_sisamorim

    # db mysql
    mysql:
        image: mysql:5.7
        container_name: mysql-sisamorim
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sisamorim
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - rede_sisamorim

    # redis
    redis:
        container_name: redis-sisamorim
        image: redis:latest
        networks:
            - rede_sisamorim

networks:
    rede_sisamorim:
        name: rede_sisamorim
        driver: bridge
