version: "3.7"

services:
    app:
        container_name: api-sisamorim
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - rede-sisamorim
        entrypoint: ["sh", "docker/app/docker-entrypoint.sh"]

    nginx:
        container_name: nginx-sisamorim
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 9001:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - rede-sisamorim

    mysql:
        image: mysql:5.7
        container_name: mysql-sisamorim
        restart: unless-stopped
        environment:
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_DATABASE=sisamorim
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - rede-sisamorim

networks:
    rede-sisamorim:
        name: rede-sisamorim
        driver: bridge
